name: action-slack
description: You can notify slack of GitHub Actions.
author: nkmadusanka
inputs:
  username:
    description: override the legacy integration's default name.
    default: ""
    required: false
  icon_url:
    description: an icon image URL string to use in place of the default icon.
    default: ""
    required: false
  channel:
    description: override the legacy integration's default channel. This should be an ID, such as C8UJ12P4P.
    default: ""
    required: false
  tag_sha:
    description: Tag event sha.
    default: ""
    required: false
  color:
    description: color
    default: ""
    required: false
runs:
  using: node12
  main: dist/index.js
branding:
  icon: bell
  color: blue
