on:
  workflow_dispatch: 
    
name: Pi release
jobs:
  niro:
    name: niro test
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: nkmadusanka/action-slack@master
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_sha: "1fc11000fdfb43a3e9f1b7620ba8ca7c054bac7d"
          username: ${{github.event.sender.login}}
          icon_url: ${{github.event.sender.avatar_url}}
          color: green

