on:
  workflow_dispatch: 
    
name: Pi release
jobs:
  niro:
    name: niro test
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: nkmadusanka/action-slack@master
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          info: |
            {
              "node_id": "MDM6VGFnNjgyOTIxMDoxZmMxMTAwMGZkZmI0M2EzZTlmMWI3NjIwYmE4Y2E3YzA1NGJhYzdk",
              "sha": "1fc11000fdfb43a3e9f1b7620ba8ca7c054bac7d",
              "url": "https://api.github.com/repos/xeneta/pi/git/tags/1fc11000fdfb43a3e9f1b7620ba8ca7c054bac7d",
              "tagger": {
                "name": "nkmadusanka",
                "email": "niroshana.madusanka@xeneta.com",
                "date": "2021-08-12T11:48:49Z"
              },
              "object": {
                "sha": "9cf79ea8e9884ea9ade0b9b450b7f5aea023533a",
                "type": "commit",
                "url": "https://api.github.com/repos/xeneta/pi/git/commits/9cf79ea8e9884ea9ade0b9b450b7f5aea023533a"
              },
              "tag": "r410.0",
              "message": "test",
              "verification": {
                "verified": false,
                "reason": "unsigned",
                "signature": null,
                "payload": null
              }
            }
        with:
          status: custom
          custom_payload: |
            {
              username: '${{github.event.sender.login}}',
              icon_url: '${{github.event.sender.avatar_url}}',
              channel: 'tech',
              attachments: [
                {
                  color: 'green',
                  title: 'Release tag created: test',
                  title_link: 'https://github.com/xeneta/pi/releases/tag/test',
                  text: "${{ fromJson(env.info).message }}"
                }
              ]
            }
