on:
  push:
    branches:
      - "!*"
    tags:
      - "r*"
    
name: Release notification
jobs:
  notification:
    name: Notify on Slack
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: nkmadusanka/action-slack@master
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_sha: ${{github.event.after}}
          username: ${{github.event.sender.login}}
          icon_url: ${{github.event.sender.avatar_url}}
          color: green
          owner: nkmadusanka
          repo: action-slack

